#!/usr/bin/env python3
# Copyright 2026 SecondSign contributors
# SPDX-License-Identifier: Apache-2.0
"""Render the contributor list from the Git history.

`CONTRIBUTORS.md` used to say that the living list was the Git history, which
was true and unhelpful: a person deciding whether this project accepts outside
work cannot read a shortlog from the README, and a list nobody generates is a
list that goes wrong the first time it is edited by hand.

So it is derived, like `docs/slices/STATUS.md`. The history is the record; this
file is a rendering of it, and no one is asked to remember to add a name.

**Ordered by first contribution, and carrying no counts or dates.** That is
deliberate. A list with commit counts changes on every merge, so the committed
copy is stale almost always, and a freshness check on it would fail on
everybody's pull request for a reason that has nothing to do with their change.
Ordered by first appearance, the file changes exactly once per person — when
they arrive — which is the only event worth a diff.

**Bots are excluded.** Dependabot lands commits here and certifies them with a
sign-off, which is a mechanical assertion by a machine account. Listing it
beside people would make "contributor" mean two different things in one file,
and it is the human list that a licence question is ever asked about.

**One person, one entry.** Git identity is whatever was configured on the
machine that made the commit, so the same person appears twice as soon as they
change laptops. `.mailmap` is where that is fixed, and `%aN`/`%aE` apply it —
which is why this tool reads those and not `%an`/`%ae`.

    python tools/render_contributors.py            # write CONTRIBUTORS.md
    python tools/render_contributors.py --check    # fail if the committed copy is stale
    python tools/render_contributors.py --stdout   # print, write nothing
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CONTRIBUTORS = REPO_ROOT / "CONTRIBUTORS.md"

#: The maintainer is a role, not a fact about the history: it says who answers a
#: security report and who can merge, neither of which a commit records. It is
#: the one part of this file that is stated rather than derived.
MAINTAINERS = (("Irene", "Bestpart-Irene"),)


def display(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def git(*args: str) -> str:
    executable = shutil.which("git")
    if executable is None:
        raise RuntimeError("git executable not found")
    result = subprocess.run(  # noqa: S603 — resolved executable, fixed arguments
        [executable, "-C", str(REPO_ROOT), *args],
        capture_output=True,
        text=True,
        check=False,
    )
    return result.stdout if result.returncode == 0 else ""


def trunk() -> str:
    """The ref to read history from.

    `origin/main` first, for the same reason the roadmap renderer prefers it: on
    a pull request checkout the local `main` may be absent or behind, and a
    contributor list read from a stale trunk silently drops whoever arrived
    most recently.
    """
    for candidate in ("origin/main", "main", "HEAD"):
        if git("rev-parse", "--verify", "--quiet", candidate).strip():
            return candidate
    return "HEAD"


def is_bot(name: str, email: str) -> bool:
    """A machine account, not a person.

    Matched on the `[bot]` suffix GitHub gives its App accounts, which is the
    form every automated committer here actually carries. A heuristic over the
    word "bot" anywhere would also catch a person named Botond.
    """
    return name.endswith("[bot]") or email.startswith("bot@") or "[bot]@" in email


def contributors(ref: str) -> list[tuple[str, str]]:
    """Every human author reachable from `ref`, in order of first commit.

    Merges are excluded: a merge commit's author is whoever pressed the button,
    so counting them would credit the maintainer with everyone else's work.
    """
    log = git("log", "--no-merges", "--reverse", "--format=%aN%x00%aE", ref)
    seen: dict[str, tuple[str, str]] = {}
    for line in log.splitlines():
        name, _, email = line.partition("\x00")
        name, email = name.strip(), email.strip()
        if not name or is_bot(name, email):
            continue
        seen.setdefault(email.lower(), (name, email))
    return list(seen.values())


def render(people: list[tuple[str, str]]) -> str:
    lines = [
        "<!-- Generated by tools/render_contributors.py. Do not edit by hand. -->",
        "<!-- Regenerate with: python tools/render_contributors.py -->",
        "",
        "# Contributors",
        "",
        "SecondSign Core is authored from scratch and Apache-2.0 licensed. Everyone",
        "below holds the copyright in their own contributions; the project holds the",
        "inbound licence Apache-2.0 §5 grants and nothing wider.",
        "",
        "This list is generated from the Git history of `main`, in order of first",
        "commit, and refreshed automatically. Nobody has to add themselves, and a name",
        "here means a commit landed — not a level of involvement.",
        "",
        "## Maintainer",
        "",
    ]
    lines.extend(
        f"- {name} — [@{handle}](https://github.com/{handle})" for name, handle in MAINTAINERS
    )
    lines.extend(
        [
            "",
            f"## Everyone who has landed a commit ({len(people)})",
            "",
        ]
    )
    if people:
        lines.extend(f"- {name}" for name, _ in people)
    else:
        lines.append("Nobody yet.")
    lines.extend(
        [
            "",
            "Avatars, handles and commit counts live on the",
            "[contributors graph](https://github.com/Bestpart-Irene/secondsign-core/graphs/contributors),",
            "which GitHub derives from the same history.",
            "",
            "## Joining the list",
            "",
            "Open a pull request — a threat case, a test, a doc fix, or a new policy",
            "dimension all count. Start from",
            "[`CONTRIBUTING.md`](CONTRIBUTING.md), which opens with the six commands a",
            "first contribution needs.",
            "",
        ]
    )
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the committed copy is stale")
    parser.add_argument("--stdout", action="store_true", help="print instead of writing")
    args = parser.parse_args(argv[1:])

    people = contributors(trunk())
    rendered = render(people)

    if args.stdout:
        print(rendered, end="")
        return 0

    if args.check:
        # A shallow checkout sees one commit and would report a repository with
        # five contributors as having one — then call the committed file stale
        # on that basis. Refusing is the honest outcome; the caller deepens the
        # history, which is what the workflow does before running this.
        if len(people) < 2:
            print(
                "FAIL: this checkout shows fewer than two contributors, so staleness\n"
                "cannot be judged. Deepen the history first:\n"
                "  git fetch --no-tags --unshallow origin main"
            )
            return 1
        current = CONTRIBUTORS.read_text(encoding="utf-8") if CONTRIBUTORS.exists() else ""
        if current == rendered:
            print(f"ok: {display(CONTRIBUTORS)} matches the history")
            return 0
        print(
            f"FAIL: {display(CONTRIBUTORS)} is stale.\n"
            "Regenerate it: python tools/render_contributors.py"
        )
        return 1

    CONTRIBUTORS.write_text(rendered, encoding="utf-8")
    print(f"wrote {display(CONTRIBUTORS)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
